/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsPointerFile {
  path: string
  hash: string
  filesize: bigint
}
export interface TokenInfo {
  token: string
  expiry: bigint
}
export declare function uploadFiles(filePaths: Array<string>, endpoint: string | undefined | null, tokenInfo: TokenInfo): Promise<Array<JsPointerFile>>
export declare function downloadFiles(files: Array<JsPointerFile>, endpoint: string | undefined | null, tokenInfo: TokenInfo): Promise<Array<string>>
