[package]
name = "chunking"
version = "0.14.5"
edition = "2021"

[dependencies]
gearhash = "0.1.3"
merklehash = { path = "../merklehash" }
mdb_shard = { path = "../mdb_shard" }
merkledb = { path = "../merkledb" }
more-asserts = "0.3.1"


[dev-dependencies]
rand = "0.9.0"
