[package]
name = "utils"
version = "0.14.5"
edition = "2021"

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
merklehash = { path = "../merklehash" }
xet_threadpool = { path = "../xet_threadpool" }
thiserror = "2.0"
futures = "0.3.28"

# singleflight
tokio = { version = "1.41", features = ["sync", "rt", "macros", "time", "io-util"] }
parking_lot = "0.11"
pin-project = "1.0.12"

# consistenthash
tracing = "0.1.31"
bytes = "1.8.0"
async-trait = "0.1.87"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tempfile = "3.14.0"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = "0.3.50"

[features]
strict = []
