[package]
name = "xorb-data-collection"
version = "0.1.0"
edition = "2021"

[dependencies]
merklehash = { path = "../merklehash"}
cas_object = { path = "../cas_object" }
utils = { path = "../utils" }
tokio = { version = "1.43.0", features = ["full"] }
aws-config = { version = "1.5.16", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.73.0", features = ["behavior-version-latest"] }
