[package]
name = "xorb-data-collection"
version = "0.1.0"
edition = "2021"

[dependencies]
merklehash = { path = "../merklehash"}
mdb_shard = { path = "../mdb_shard"}
merkledb = { path = "../merkledb"}
cas_object = { path = "../cas_object" }
data = { path = "../data" }
cas_client = { path = "../cas_client" }
xet_threadpool = {path = "../xet_threadpool"}
utils = { path = "../utils" }
cas_types = { path = "../cas_types" }
file_utils = { path = "../file_utils" }
tokio = { version = "1.43.0", features = ["full"] }
aws-config = { version = "1.5.16", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.73.0", features = ["behavior-version-latest"] }
futures = "0.3.31"
futures-util = "0.3.31"
clap = "4.5.28"
clap_derive = "4.5.28"
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
parquet = "54.1.0"
parquet_derive = "54.1.0"
rand = "0.8.5"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
